// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Guitar struct {
	ID        int64              `json:"id"`
	Brand     string             `json:"brand"`
	Model     string             `json:"model"`
	Year      *int16             `json:"year"`
	Notes     *string            `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
