// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createGuitar = `-- name: CreateGuitar :one
INSERT INTO guitars (
    brand,
    model,
    year,
    notes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, brand, model, year, notes, created_at, updated_at
`

type CreateGuitarParams struct {
	Brand string  `json:"brand"`
	Model string  `json:"model"`
	Year  *int16  `json:"year"`
	Notes *string `json:"notes"`
}

func (q *Queries) CreateGuitar(ctx context.Context, arg CreateGuitarParams) (Guitar, error) {
	row := q.db.QueryRow(ctx, createGuitar,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.Notes,
	)
	var i Guitar
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGuitar = `-- name: DeleteGuitar :exec
DELETE FROM guitars WHERE id = $1
`

func (q *Queries) DeleteGuitar(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGuitar, id)
	return err
}

const findGuitarByID = `-- name: FindGuitarByID :one
SELECT id, brand, model, year, notes, created_at, updated_at FROM guitars WHERE id = $1
`

func (q *Queries) FindGuitarByID(ctx context.Context, id int64) (Guitar, error) {
	row := q.db.QueryRow(ctx, findGuitarByID, id)
	var i Guitar
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuitars = `-- name: ListGuitars :many
SELECT id, brand, model, year, notes, created_at, updated_at FROM guitars
`

func (q *Queries) ListGuitars(ctx context.Context) ([]Guitar, error) {
	rows, err := q.db.Query(ctx, listGuitars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guitar
	for rows.Next() {
		var i Guitar
		if err := rows.Scan(
			&i.ID,
			&i.Brand,
			&i.Model,
			&i.Year,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuitar = `-- name: UpdateGuitar :one
UPDATE guitars
SET
    brand      = $2,
    model      = $3,
    year       = $4,
    notes      = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, brand, model, year, notes, created_at, updated_at
`

type UpdateGuitarParams struct {
	ID    int64   `json:"id"`
	Brand string  `json:"brand"`
	Model string  `json:"model"`
	Year  *int16  `json:"year"`
	Notes *string `json:"notes"`
}

func (q *Queries) UpdateGuitar(ctx context.Context, arg UpdateGuitarParams) (Guitar, error) {
	row := q.db.QueryRow(ctx, updateGuitar,
		arg.ID,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.Notes,
	)
	var i Guitar
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
