// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const findGuitarByID = `-- name: FindGuitarByID :one
SELECT id, brand, model, name, year, country_of_origin, body_type, body_wood, top_wood, neck_wood, fretboard_wood, scale_length, fretboard_radius, pickups_config, pickup_brand, bridge_type, tuners, color, finish, pickguard, condition, purchase_price, purchase_date, selling_price, is_for_sale, is_sold, sold_date, sold_to, weight_kg, serial_number, case_type, modifications, notes, created_at, updated_at FROM guitars WHERE id = $1
`

func (q *Queries) FindGuitarByID(ctx context.Context, id int64) (Guitar, error) {
	row := q.db.QueryRow(ctx, findGuitarByID, id)
	var i Guitar
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.Name,
		&i.Year,
		&i.CountryOfOrigin,
		&i.BodyType,
		&i.BodyWood,
		&i.TopWood,
		&i.NeckWood,
		&i.FretboardWood,
		&i.ScaleLength,
		&i.FretboardRadius,
		&i.PickupsConfig,
		&i.PickupBrand,
		&i.BridgeType,
		&i.Tuners,
		&i.Color,
		&i.Finish,
		&i.Pickguard,
		&i.Condition,
		&i.PurchasePrice,
		&i.PurchaseDate,
		&i.SellingPrice,
		&i.IsForSale,
		&i.IsSold,
		&i.SoldDate,
		&i.SoldTo,
		&i.WeightKg,
		&i.SerialNumber,
		&i.CaseType,
		&i.Modifications,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuitars = `-- name: ListGuitars :many
SELECT id, brand, model, name, year, country_of_origin, body_type, body_wood, top_wood, neck_wood, fretboard_wood, scale_length, fretboard_radius, pickups_config, pickup_brand, bridge_type, tuners, color, finish, pickguard, condition, purchase_price, purchase_date, selling_price, is_for_sale, is_sold, sold_date, sold_to, weight_kg, serial_number, case_type, modifications, notes, created_at, updated_at FROM guitars
`

func (q *Queries) ListGuitars(ctx context.Context) ([]Guitar, error) {
	rows, err := q.db.Query(ctx, listGuitars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guitar
	for rows.Next() {
		var i Guitar
		if err := rows.Scan(
			&i.ID,
			&i.Brand,
			&i.Model,
			&i.Name,
			&i.Year,
			&i.CountryOfOrigin,
			&i.BodyType,
			&i.BodyWood,
			&i.TopWood,
			&i.NeckWood,
			&i.FretboardWood,
			&i.ScaleLength,
			&i.FretboardRadius,
			&i.PickupsConfig,
			&i.PickupBrand,
			&i.BridgeType,
			&i.Tuners,
			&i.Color,
			&i.Finish,
			&i.Pickguard,
			&i.Condition,
			&i.PurchasePrice,
			&i.PurchaseDate,
			&i.SellingPrice,
			&i.IsForSale,
			&i.IsSold,
			&i.SoldDate,
			&i.SoldTo,
			&i.WeightKg,
			&i.SerialNumber,
			&i.CaseType,
			&i.Modifications,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
